services:
  postgres:
    image: postgres:latest
    container_name: postgres_avmb
    restart: always
    environment:
      POSTGRES_USER: doc
      POSTGRES_PASSWORD: doc123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql # Script de inicialização (opcional)
      - ./db/postgresql.conf:/etc/postgresql/postgresql.conf # Configuração personalizada (opcional)

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    # env_file: 
    #   - .backend/dist
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres

  server:
    build: ./frontend
    ports:
      - "80:80"
    # env_file: 
    #   - .backend/dist
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  frontend:
    build: ./frontend/dev.Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - backend
    volumes:
      - .:/app

volumes:
  pgdata:
