POST http://localhost:3000/admin/permissions
Content-Type: application/json
Authorization: Bearer jwt

{
  "name": "manager",
  "slug": "manager",
  "description": "Permite admnistrar aprte do sistema"
}

###
GET http://localhost:3000/admin/permissions
Authorization: Bearer {{ jwt }}

###
GET http://localhost:3000/admin/permissions/3
Content-Type: application/json

###
PATCH http://localhost:3000/admin/permissions/1
Content-Type: application/json

{
  "slug": "manager"
}

###
GET http://localhost:3000/permissions?page=Manager

###
GET http://localhost:3000/permissions/1
Content-Type: application/json

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "",
  "password": ""
}

###
# @name admin_jwt_login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "manager@user.com",
  "password": "manager123"
}

###
@jwt = {{ admin_jwt_login.response.body.access_token }}