POST http://localhost:3000/admin/permissions
Content-Type: application/json
Authorization: Bearer jwt

{
  "name": "manager",
  "slug": "manager",
  "description": "Permite admnistrar aprte do sistema"
}

###
GET http://localhost:3000/admin/permissions
Authorization: Bearer {{ jwt }}

###
GET http://localhost:3000/admin/permissions/3
Content-Type: application/json

###
PATCH http://localhost:3000/admin/permissions/1
Content-Type: application/json

{
  "slug": "manager"
}

###
GET http://localhost:3000/permissions

###
GET http://localhost:3000/permissions/1

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "",
  "password": ""
}

### LOGIN
# @name admin_jwt_login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "admin@user.com",
  "password": "admin123"
}

###
@jwt = {{ admin_jwt_login.response.body.access_token }}



# USERS
### CREATE USER
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Ash Katchun",
  "email": "user@pkm.com",
  "birthday": "1989-06-14T00:00:00.000Z",
  "password": "user123"
}

### LIST USERS
GET http://localhost:3000/users
Authorization: Bearer {{ jwt }}

### EDIT USER
PATCH  http://localhost:3000/users/df44eb6d-f5bd-4d22-a8a5-81ff4d359b02
Authorization: Bearer {{ jwt }}
Content-Type: application/json

{
  "email": "adm@pkm.com"
}

### DELETE USER
DELETE http://localhost:3000/admin/users/b8cb6771-d224-48db-8848-f42779402e31
Authorization: Bearer {{ jwt }}



